### ISSUE TITLE
Multi-line replacements?

### ISSUE THREAD

**Issue by wayneashleyberry** [yoniholmes/grunt-text-replace#12]
Are multi-line replacements supported? I'm struggling to get them working...

``` javascript
{
  from: "foo\nbar",
  to: "foobar"
}
```

**Comment by wayneashleyberry** [comment]
nvm, got it :)

**Comment by rusekr** [comment]
I 'am too. 
Why it's not working?

Tried to use that fine regex https://regex101.com/r/Crs1bX/1 but need to search another replacer because of that small neuance.
