### ISSUE TITLE
Is it possible to not overwrite when no matches are found?

### ISSUE THREAD

**Issue by old9** [yoniholmes/grunt-text-replace#15]
This would be useful in the overwrite mode.

**Comment by yoniholmes** [comment]
Hi there old9. Sorry for the delay in responding to your request. I'm afraid I don't quite understand what you mean here. What's the use case? I took at look at your pull request, but didn't understand why you'd want to overwrite a file that's identical - wouldn't that be equivalent to not overwriting it? Perhaps I've misunderstood. If you can clarify for me what you mean, I'll reconsider the pull request. 

Many thanks, 

Jonathan

**Comment by old9** [comment]
Well the use case is, in overwrite mode, I don't want to do a overwrite when two files are identical(no matches are found). Since I got a problem when working with watch, an unnecessary overwrite would trigger an unnecessary watch task.

and the PR's meant to set a option for whether or not to overwrite, when the contents are identical, both in overwrite mode and copy mode.

When it's in overwrite mode, the `forceOverwrite` option is default to false(not to overwrite when identical)
when it's in copy mode, the `forceCopy` option is default to true(still copies even identical)

**Comment by yoniholmes** [comment]
Closing this, given this is covered in #16. Cheers, Jonathan
