### ISSUE TITLE
Load replacements from .json file

### ISSUE THREAD

**Issue by samyerkes** [yoniholmes/grunt-text-replace#18]
I'm finding this plugin really helpful in my current workflow for my university's CMS, thank you! I was wondering though if there was a way to load replacements from a .json file instead of directly stating them in the .gruntfile? Currently I have about 40 replacements so my gruntfile is getting quite large.

**Comment by yoniholmes** [comment]
Hi Sam, 

Thanks for your message - yes that's quite easy to achieve using grunt itself. I've had to do the same before. I expect there are several ways to achieve this, here's one:
1.  Put all your replacements in a JSON file. For example, this might just be an array of replacement objects.
2.  Create a new task to process these replacements
3.  Use grunt's readJSON method to read the JSON file. 
4.  Use grunt's config method to set your replace object's 'replacements' property to be equal to the one you read from the JSON file. 
5.  Run the 'replace' task, then you're done. 

Here's an example:

``` javascript
  grunt.initConfig({   
    replace: {
      example: {
        src: ['test.txt'],
        overwrite: true,                 
        replacements: []   // this is going to get replaced from replacements.json
      }
    }
  });

  grunt.registerTask('make-replacements', function () {
    var replacements = grunt.file.readJSON('replacements.json');
    grunt.config('replace.example.replacements', replacements);
    grunt.task.run('replace');
  });

  grunt.registerTask('default', ['make-replacements']);
```

Hope it helps!

Cheers, 

Jonathan

**Comment by samyerkes** [comment]
This is great, thank you so much for the great plugin! Like I said, it's really making my workflow at work a breeze.

**Comment by yoniholmes** [comment]
No worries, happy coding. =)

Jonathan

**Comment by lunelson** [comment]
I'm also trying to use JSON as a source for replacements (though in a way which is best explained if you check out the thread at outaTiME/grunt-replace/issues/37); but my problem is that the JSON is only loaded at the start of a `grunt watch`, and not checked again before the replace task runs. The workflow describe above looks more promising, but I'd want to supply a function to `replacements`, so I can parse through the JSON to dynamically create an array of objects with `from:` and `to:` values... would that be possible?

**Comment by lunelson** [comment]
This is my attempt to do something like this, creating a recognizable search string as with the other plugin mentioned in my previous comment

``` js
    replace: { // https://github.com/yoniholmes/grunt-text-replace
      mixture: {
        src: ['mixture.yml'],
        dest: 'mixture.temp.yml',
        replacements: function() {
          var repl = [];
          var jsonRepl = grunt.file.readJSON('mixture.json');
          for (var key in jsonRepl) { repl.push({
            from: '@@' + key,
            to: jsonRepl[key]
          }); }
          return repl;
        }
      },
    },
```
