### ISSUE TITLE
"Remove Support"

### ISSUE THREAD

**Issue by PunkChameleon** [yoniholmes/grunt-text-replace#20]
Hey all,

Is there a way to just remove a line, instead of replacing it with '' ? I think it'd be fairly helpful in dev to prod situations.

Hope this helps!
N

**Comment by yoniholmes** [comment]
Hi there Nick, 

Thanks for your suggestion, it's always welcome. I've given it some thought - I can't think of a convenient notation for describing this that would differentiate removing the match plus the surrounding new line characters, as opposed the current functionality of removing just the match and replacing it with an empty string. 

It's already possible to achieve the effect you're after, but requires a regex search to find the adjacent new line characters (as opposed to a string search). 

For those reasons I'm going to mark the issue as closed. I'm happy however to receive a pull request or further ideas if you have them. 

Thanks again, 

Jonathan
