### ISSUE TITLE
Git tag

### ISSUE THREAD

**Issue by prcaen** [yoniholmes/grunt-text-replace#21]
Hello,

I will be nice if you tag each version of this plugin.

Many thanks before
P.

**Comment by yoniholmes** [comment]
Hey, sorry I didn't reply way back when you wrote this. Yes, that's a good idea. I've not done this yet, will leave this open until I implement this for future releases. Thanks, Jonathan

**Comment by yoniholmes** [comment]
Hi there. So at long last I've pushed an update to grunt-text-replace. I also realised that the reason you couldn't see tags is that I hadn't pushed them from my repo correctly up to github. Most are there now. Closing this issue. Thanks again for raising it. Cheers, Jonathan
