### ISSUE TITLE
File encoding changes on replace

### ISSUE THREAD

**Issue by nabils** [yoniholmes/grunt-text-replace#23]
I am trying to run a replace with overwrite option set to true. This works but for all files including the ones where there were no matches it will change the file encoding from UTF8 to unicode. Any ideas why this is happening? Ideally I would not want the encoding to change at all, especially for files with no matches should not be touched.

Thanks

**Comment by yoniholmes** [comment]
Hi Nabil, 

Thanks for your message. I wanted to ask are you seeing any faulty behaviour as a result of using grunt.text.replace? Also, how are you checking what the file encoding is? Note that Unicode is a character set and UTF-8 is an encoding that uses the Unicode character set. See [the difference between UTF-8 and Unicode](http://www.rrn.dk/the-difference-between-utf-8-and-unicode). 

As for grunt.text.replace, it uses [grunt.file.copy](http://gruntjs.com/api/grunt.file#grunt.file.copy) to write files, both for overwriting and creating new files. Grunt.file.copy uses UTF-8 as a default character encoding, so all files should be UTF-8. You can see the [replacement code here](https://github.com/yoniholmes/grunt-text-replace/blob/master/lib/grunt-text-replace.js#L42).

Let me know if you track down the issue any further, and if you need any help. If anything needs changing feel free to fork and submit a pull request. 

I'm going to mark this issue as closed but reopen if you feel there still exists a problem, and if you could provide a bit more information about the problems you're seeing.

Thanks, 

Jonathan

**Comment by nabils** [comment]
Sorry didn't explain very well but this is related to https://github.com/yoniholmes/grunt-text-replace/pull/16

**Comment by nabils** [comment]
Are you able to merge this pull request and release a new version to npm please? 
This is the only way to stop it updating every file regardless of if there were changes.

https://github.com/yoniholmes/grunt-text-replace/pull/16
