### ISSUE TITLE
Encoding and force options?

### ISSUE THREAD

**Issue by elebetsamer** [yoniholmes/grunt-text-replace#24]
Would it be possible to add an encoding option? My source files are UTF-8 and but after running the replace my files were converted to ANSI. Maybe you can add an encoding option like the one available for https://www.npmjs.org/package/grunt-replace?

It would also be nice to have an option like the "force" option on that other package too. It seems running this package causes all my files to be modified even though the contents of the file have actually not changed. This makes it a bit of a pain for git since it shows that I basically need to commit all files that I run the replace for.

**Comment by elebetsamer** [comment]
Just noticed it is only converting to ANSI for files that are UTF-8 with BOM. UTF-8 without BOM and all other files seem to be getting left alone. This is also why it is marking a very large number of my files as modified, even though the contents aren't actually modified.

In any case, it might still be nice to have the encoding option available. Though I can't say if the force option would still be needed.

**Comment by elebetsamer** [comment]
After some more playing around, putting grunt.file.preserveBOM = true; before my initConfig helped to stop the conversion of my files ANSI. But all processed files are still being marked as modified even if their contents did not change, so that is still an issue.

**Comment by yoniholmes** [comment]
Hey, thanks for your messages. Yes another person raised this recently. I use grunt.file.copy (just once you can see it in the source code), but figure what's needed is a check to prevent this from getting run if there's no text change, and if file overwriting is set to true. I believe that would make a 'force replace' option redundant. The grunt.file.copy would however need to be run if there were no changes but the user opted to export text changes to another directory. 

I'll look at this as soon as I can (over weekend if I can). 

Alternatively I'll happily accept a pull request that passes the current tests. Would be good to add a test to ensure files aren't getting replaced too. 

Cheers,

Jonathan

**Comment by yoniholmes** [comment]
Just to let you know, I've not forgotten this, but have been pretty busy. As before, am happy to receive a pull request if this is urgent for you, otherwise will implement myself when I get some time. 

Cheers, 

Jonathan

**Comment by yoniholmes** [comment]
Hi there. Ok I've updated grunt-text-replace (v0.4.0) so that it doesn't make modifications to files where no replacements are required. That should fix the 'processed files are still being marked as modified even if their contents did not change' problem. Let me know how you get on.
