### ISSUE TITLE
Is this plugin compatible with the new grunt 4.0?

### ISSUE THREAD

**Issue by MMRandy** [yoniholmes/grunt-text-replace#3]
Looks awesome, would love to use this in place of another string replace plugin I am currently using, but can't unless it supports 4.0.  Thx...

**Comment by yoniholmes** [comment]
Hi MMRandy, thanks for your message. Yeah I haven't tested grunt 4.0, but I need to. I'll try to take a look this week, or possibly by the weekend. Otherwise, if you have the appetite for it, I'd be happy to review a pull request. 

Cheers & will let you know if I push an update. 

Jonathan

**Comment by MMRandy** [comment]
I have the appetite, but not sure if I have the skills or the bandwidth :)   I need to dive in one weekend and just write a plugin and get it over with.  Thanks for the update!

**Comment by yoniholmes** [comment]
Fair enough. If you want to write your own plugin, and if you hadn't already worked it out, the easiest way to start is from your command line:  grunt init:gruntplugin. You'll need to consult the internet from that point! Good luck. 

Again, will let you know if I get the plugin updated to support grunt 4.0. 

Cheers, 

Jonathan

**Comment by MMRandy** [comment]
Hey Jonathan...any updates to report?  I'm trying to wrap my brain around 4.0, have upgraded most of my gruntfile's tasks already, only a couple remain.  I cannot seem to find a 0.4.x compatible regex search & replace plugin.  Maybe we could get some of the Grunt folks to help out here on the upgrade?  They seem to have recently reverted a change to the this.files object...which is causing problems in some plugins, so things are still a little unstable.

**Comment by yoniholmes** [comment]
Hi MMRandy, thanks for your message. No - haven't yet been able to get to this I'm afraid, but I have made a start. I'll surely let you know once I push an update. Many thanks, Jonathan

**Comment by yoniholmes** [comment]
Hi MMRandy, just to let you know that I've updated the plugin to 0.3.0 which is now grunt 4.0 compatible. grunt-text-replace 0.3.0 is no longer grunt 0.3.x compatible though I'm afraid. Let me know if you come across any issues. Thanks again, Jonathan

**Comment by MMRandy** [comment]
Awesome, thanks Jon...I'll give it a go tomorrow.  Thanks again for the update :)
