### ISSUE TITLE
Replace only for first occurrence

### ISSUE THREAD

**Issue by AlexandreKilian** [yoniholmes/grunt-text-replace#30]
Currently, only the first occurance of a pattern is being replaced...

**Comment by yoniholmes** [comment]
Hi Alexandre,

Do you have a code example? Note that string replace should be global (ie.
not just first instance) but regex behaves like a normal regex (ie. will
replace first instance only unless you add the global flag: g).

Cheers,

Jonathan

**Comment by eruizdechavez** [comment]
@yoniholmes I am 99.999999% sure it is a problem on the regex. I got the same report at https://github.com/erickrdch/grunt-string-replace/issues/26.

**Comment by yoniholmes** [comment]
Thanks Erick. Marking as closed for now. I've unit tests in place to test for this very case, so I suspect it's the missing /g flag. Cheers, Jonathan

**Comment by AlexandreKilian** [comment]
sorry, my bad, this was an issue-report after hours of battling with different different grunt-modules, actually forgot the /g when switching back to regex...

**Comment by yoniholmes** [comment]
No problem @AlexandreKilian, pleased you fixed your issue. Cheers, Jonathan
