### ISSUE TITLE
Option to disable template processing

### ISSUE THREAD

**Issue by herrkris** [yoniholmes/grunt-text-replace#5]
Hey everybody,

as mentioned (https://github.com/gruntjs/grunt/issues/667) I wonder if it's possible to build in an option to disable template processing.

```
  grunt.initConfig({
    replace: {
      stylesheets: {
        src: "build/stylesheets/**",
        overwrite: true,
        replacements: [{
          from: /url\([^)]*\)/gi,
          to: function(matched) {
            // some processing going on here
            return 'url(<%' + matched + '%>)';
          }
        }]
      }
    }
  });
};
```

The problem is the return value. Jonathan told me, that every return value gets processed, so it would be nice, if I could disable it.

My output should look like this: `url(<%something%>)`

Kind Regards,
Kristof

**Comment by yoniholmes** [comment]
Hi Kristof, 

I hope you're well. I've made an update to grunt-text-replace to accomodate your needs, you can check out the docs at:  https://github.com/yoniholmes/grunt-text-replace#options. This works as of grunt-text-replace 0.3.2.

_Note_ this only works for return statements within functions. Unfortunately grunt processes all config values that are strings, before they are made available to the plugin. For future reference, this occurs in grunt at:  https://github.com/gruntjs/grunt/blob/f9071ef0eefa80222444f23fd7998043425c0958/lib/grunt/config.js#L75. So in other words, if we'd like processTemplates: false to apply to replacements that are just strings, we'll need to get the grunt guys to change that line of code somehow. I won't pursue this for now.

I hope it helps. Let me know if there are any issues. 

Cheers, 

Jonathan
