### ISSUE TITLE
Size of spritesheet

### ISSUE THREAD

**Issue by davidtheclark** [yoniholmes/grunt-text-replace#8]
When I look at the generated spritesheet, I see that all the sprites are in one vertical line, instead of being smartly arranged to minimize space. This results in a spritesheet that is about 4x larger than a spritesheet I generated from the same images using [glue](http://glue.readthedocs.org/en/latest/). I'd prefer to use your plugin because it outputs such nice SCSS -- but this inefficiency is killing it for me. Is there some configuration I should be changing, or is smarter arrangement just not built into the plugin?

**Comment by yoniholmes** [comment]
Hi there. Are you able to clarify what problem you're facing with grunt-text-replace exactly? Or perhaps show some examples? 

Many thanks!

Jonathan

**Comment by davidtheclark** [comment]
I'm sorry! I put this comment on the wrong github project! I'm closing the issue. Sorry again!

**Comment by yoniholmes** [comment]
No worries!

Cheers, 

Jonathan
