### ISSUE TITLE
How to specify specific replacements for specific files?

### ISSUE THREAD

**Issue by CMCDragonkai** [yoniholmes/grunt-text-replace#9]
I'm using src with an array of files, and then overwrite. But how do I specify which replacements are related to which files? Do all the replacements occur to all the files?

**Comment by yoniholmes** [comment]
Hi there. Thanks for your message. I'll try to clarify for you. 

**src** - a white list of the files that grunt-text-replace is going to run through. 
**dest** - a directory where the reviewed src files will be output to. Not used in conjunction with 'overwrite'.
**overwrite** - 'true' if you give grunt-text-replace permission to overwrite the src files that you'd like to run through if there are changes.

So, you specify replacements via the **src** attribute. If you'd like to make different sets of overwrites to different files then specify additional [grunt targets](https://github.com/gruntjs/grunt/wiki/Configuring-tasks#task-configuration-and-targets). Here's a contrived example:

```
replace:
  changeJonathanSpelling: {
    src: ['names.html'],
    overwrite: true,                
    replacements: [{ 
      from: 'Jonathon',
      to: 'Jonathan'
    }],
  }, 
  changeDay: {
    src: ['days.html'],
    overwrite: true,                 
    replacements: [{ 
      from: 'Tuesday',
      to: 'Wednesday'
    }]
  }
}
```

Let me know if that doesn't answer your question. 

Cheers, 

Jonathan
